// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9HsBLqK0ga6Y-UWnwew2INpmtzv7QyY',
    appId: '1:427675975131:web:722376dbaa84a74f417bfe',
    messagingSenderId: '427675975131',
    projectId: 'gpsapplication-15afc',
    authDomain: 'gpsapplication-15afc.firebaseapp.com',
    storageBucket: 'gpsapplication-15afc.firebasestorage.app',
    measurementId: 'G-PTFZ0TRK98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnIEpk5aPROXyMhzeAw7jb1Z7AvQqBmU',
    appId: '1:427675975131:android:a6815543aee02d34417bfe',
    messagingSenderId: '427675975131',
    projectId: 'gpsapplication-15afc',
    storageBucket: 'gpsapplication-15afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9IVIKDsEPX571TYww2ELnSzHJfHTlePA',
    appId: '1:427675975131:ios:da89c23291bbc878417bfe',
    messagingSenderId: '427675975131',
    projectId: 'gpsapplication-15afc',
    storageBucket: 'gpsapplication-15afc.firebasestorage.app',
    iosBundleId: 'com.territorywalk.territoryWalk',
  );
}
